In [1]:
from IPython.core.display import HTML, display
encabezado=display(HTML(' <div style="background-color: #023324; "><p>'+
             '<br></p>     <img src="https://www.uexternado.edu.co/wp-content/themes/externado_theme/images/logo-uec.svg" alt="Universidad Externado" width="150" align="left">  '+
             '<h1  style="color: white;font-family:Lucida Sans Unicode, Lucida Grande, sans-serif" align="center">Clase 23: Juegos contra la Naturaleza y Valor Esperado</h1> '+
             '<p><br></p></div>'))

**Profesor: David Andrés Franco Quintero**

**Materia: Matemáticas para Derecho**

# Clase 23: Juegos contra la Naturaleza y Valor Esperado

## Ejercicio

NARANJO MARTÍNEZ, C. *Lecciones de Matemáticas para Abogados 2.0* Universidad Externado de Colombia. Bogotá D. C. 2013. 88 p. y ss.

Un inversionista está interesado en adquirir bonos del tesoro, armamento, o un portafolio de acciones en un país que ofrece cierta expectativa de fortaleza económica, pero que aún se encuentra en una situación difícil de orden público. Tal es así, que el inversionista podría haberse enfrentado a un ambiente de guerra fría entre las fuerzas militares del Estado y los grupos insurgentes o a una situación de paz o incluso a una situación de enfrentamiento total. Las recompensas que se obtienen según cada situación y decisión de inversión que tomen son las mostradas en la matriz de pagos siguiente y corresponden a la utilidad en millones de pesos.

In [2]:
import numpy as np
from numpy import *
import pandas as pd
B=np.array([[160,200,70],[280,60,400],[320,360,-80]])
print(B)
estrategias=("Bonos del Tesoro","Armamento","Portafolio de acciones")
naturaleza=("Guerra Fría","Paz","Enfrentamiento")
tabla=pd.DataFrame(B,index=estrategias,columns=naturaleza)
tabla

[[160 200  70]
 [280  60 400]
 [320 360 -80]]


Guerra Fría  Paz  Enfrentamiento
Bonos del Tesoro                160  200              70
Armamento                       280   60             400
Portafolio de acciones          320  360             -80

De acuerdo con esta información, resuelva:

a. ¿Por qué podría llamarse este un juego de un jugador?

b. Si el jugador fuese prudente para invertir, es decir con aversión al riesgo, ¿cuál sería el valor del juego?

c. Si el jugador fuese arriesgado para invertir, es decir propenso al riesgo, ¿cuál sería el valor del juego?

d. Suponga que hay una probabilidad de 0,75 de que se dé el escenario de *Guerra Fría*, y que existe una probabilidad de 0,125 de que sea el de *Paz* el que se dé. A partir del criterio del Valor Esperado, ¿cuál debería ser la estrategia a elegir?

### Solución

a. Por dos razones:

1. Por cuanto sólo hay un personaje que toma decisiones.

2. La naturaleza no es un un jugador que toma decisiones, sino una contigencia de situaciones o ambientes posibles (los escenarios que pueden ocurrir).

b. Cuando se asume que un jugador es averso al riesgo, éste asume una posición de pensar en las peores consecuencias, pero entre ellas elige la que mayor ganancia le reporte (por ser maximizador); entre lo peor, elige lo mejor. De esta manera es alguien que busca el *maxmin* (el **máx**imo de los **mín**imos). Por eso, hay que buscar primero las mínimas recompensas de cada estrategia, para de ellas elegir la máxima.

**Mínimos:**

In [3]:
mini=[]
for row in B:
    mini.append(min(row))
minimos={"Mínimos"}
minis=pd.DataFrame(mini,index=estrategias,columns=minimos)
minis

Mínimos
Bonos del Tesoro             70
Armamento                    60
Portafolio de acciones      -80

**maxmin**

In [4]:
minis["Mínimos"].max()

70

En este sentido, una persona aversa al riesgo, elegiría el máximo de los mínimos (maxmin). Para la situación del inversionista el *maxmin* = 70, que corresponde a la estrategia "Bonos del Tesoro". Entonces, suponiendo que él sea averso al riesgo, decidiría invertir en un *Bonos del Tesoro*, esperando que se dé una situacion de "Enfrentamiento".

c. Cuando se asume que un jugador es propenso al riesgo, éste asume una posición de pensar en las mejores consecuencias, y entre ellas elige la que mayor ganancia le reporte (por ser maximizador); entre lo mejor, elige lo mejor. De esta manera es alguien que busca el *maxmax* (el **máx**imo de los **máx**imos). Por eso, hay que buscar primero las máximas recompensas de cada estrategia, para de ellas elegir la máxima.

**Máximos**

In [5]:
maxi=[]
for row in B:
    maxi.append(max(row))
maximos={"Máximos"}
maxis=pd.DataFrame(maxi,index=estrategias,columns=maximos)
maxis

Máximos
Bonos del Tesoro            200
Armamento                   400
Portafolio de acciones      360

**maxmax**

In [6]:
maxis["Máximos"].max()

400

En este sentido, una persona propensa al riesgo, elegiría el máximo de los máximos (maxmax). Para la situación del inversionista el *maxmax* = 400, que corresponde a la estrategia "Armamento". Entonces, suponiendo que él sea propenso al riesgo, decidiría invertir en *Armamento*, esperando que se dé una situación de "Enfrentamiento".

d. En este punto el Valor Esperado (o Esperanza Matemática) de cada estrategia, dicta lo que se esperaría en promedio de elegir cada una de los opciones (conociendo lo bueno y lo malo de cada estrategia, y la probabilidad de que se dé cada escenario).

Ya que la "Paz" tiene una probabilidad de 0,125 de darse, y la "Guerra Fría" una de 0,75, entonces el de "Enfrentamiento" tiene una probabilidad de 0,125 (¿por qué?). Así, la tabla queda:

In [7]:
naturaleza=("Guerra Fría (0,75)","Paz (0,125)","Enfrentamiento (0,125)")
tabla2=pd.DataFrame(B,index=estrategias,columns=naturaleza)
tabla2

Guerra Fría (0,75)  Paz (0,125)  \
Bonos del Tesoro                       160          200   
Armamento                              280           60   
Portafolio de acciones                 320          360   

                        Enfrentamiento (0,125)  
Bonos del Tesoro                            70  
Armamento                                  400  
Portafolio de acciones                     -80

De esta manera, debemos hacer lo siguiente para cada estrategia posible:

1. Cada ganancia que pueda presentarse en la estrategia, debe multiplicarse con su respectiva probabilidad de ocurrencia (esto depende de en qué escenario de la naturaleza se manifiesta). Ejemplo: Si se elige la estrategia "Bonos del Tesoro", el 160 se presenta con una probabilidad de 0,75 (que se dé una "Guerra Fría").

2. Cada uno de los resultados de las multiplicaciones de la estragia debe ser ser sumado. Ejemplo: Para la estrategia "Bonos del Tesoro" se tiene que E(Bonos del Tesoro) = (160 x 0,75) + (200 x 0,125) + (70 x 0,125) = 153,75

3. El Valor Esperado es el resultado del paso anterior. Se debe elegir el que mayor Valor Esperado reporte.

In [8]:
print(B)
#B1=transpose(B)
#print(B1)
contador_filas=0
probabilidades=[0.75,0.125,0.125]
probabilidades2=[]
while contador_filas<len(estrategias):
    probabilidades2.append(probabilidades)
    contador_filas+=1
probabilidades3=np.array(probabilidades2)
print()
print(probabilidades3)
print()
prob2=probabilidades3*B
print(prob2)

[[160 200  70]
 [280  60 400]
 [320 360 -80]]

[[0.75  0.125 0.125]
 [0.75  0.125 0.125]
 [0.75  0.125 0.125]]

[[120.    25.     8.75]
 [210.     7.5   50.  ]
 [240.    45.   -10.  ]]


In [9]:
VEs=np.apply_along_axis(sum, 1, prob2) #0 para operar sobre columnas, 1 para operar sobre filas 
VEs

array([153.75, 267.5 , 275.  ])

In [10]:
valoresesperados=["Valores Esperados"]
tabla3=pd.DataFrame(VEs,index=estrategias,columns=valoresesperados)
tabla3

Valores Esperados
Bonos del Tesoro                   153.75
Armamento                          267.50
Portafolio de acciones             275.00

Así, debe elegir la estrategia que reporte el mayor valor esperado.

In [11]:
tabla3["Valores Esperados"].max()

275.0

Entonces la estrategia que debería elegirse, de acuerdo con el Valor Esperado, es la del Portafolio de acciones.

## Solucionador de Juegos contra la Naturaleza

### Por criterios de aversión y propensión al riesgo

In [2]:
import numpy as np
import pandas as pd
from numpy import *

def creadortabla(num_estrategias,num_naturaleza):
    valori=np.zeros((num_estrategias,num_naturaleza))
    tabla=pd.DataFrame(valori)
    print(tabla)
    
creadortabla(2,1)

     0
0  0.0
1  0.0
